language: node_js
node_js:
    - 4.2
notifications:
    email:
        recipients:
            - szlem01+travis@gmail.com
        on_success: always
        on_failure: always
before_install:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - npm install
    - make test

install: true
